flutter_app: 
  command: ecg_media
  arch: x64
  parent: /usr/local/lib

control:
  Package: ECG-Mediathek
  Version: 1.0.0
  Architecture: amd64
  Essential: no
  Priority: optional
  Depends: libsecret-1-0 and libjsoncpp1
  Maintainer: WeKoDe
  Description: A custom media library!